export const ACCESS_CLIENT = 'ACCESS_CLIENT'
export const ACCESS_DASHBOARD = 'ACCESS_DASHBOARD'
export const VIEW_USER = 'VIEW_USER'
export const VIEW_CATEGORY = 'VIEW_CATEGORY'
export const VIEW_ARTICLE = 'VIEW_ARTICLE'
export const VIEW_PROJECT = 'VIEW_PROJECT'
export const VIEW_TICKET = 'VIEW_TICKET'
export const VIEW_ROLE = 'VIEW_ROLE'
export const ADD_USER = 'ADD_USER'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const ADD_PROJECT = 'ADD_PROJECT'
export const EDIT_USER = 'EDIT_USER'
export const EDIT_ROLE = 'EDIT_ROLE'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const EDIT_ARTICLE = 'EDIT_ARTICLE'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const EDIT_TICKET = 'EDIT_TICKET'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_ROLE = 'DELETE_ROLE'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_TICKET = 'DELETE_TICKET'
export const COMMENT_ARTICLE = 'COMMENT_ARTICLE'
export const COMMENT_PROJECT = 'COMMENT_PROJECT'
export const PURPOSE_PROJECT = 'PURPOSE_PROJECT'
export const PURPOSE_ARTICLE = 'PURPOSE_ARTICLE'
export const CHATTING = 'CHATTING'

export default [
  ACCESS_CLIENT,
  ACCESS_DASHBOARD,
  VIEW_USER,
  VIEW_CATEGORY,
  VIEW_ARTICLE,
  VIEW_PROJECT,
  VIEW_TICKET,
  VIEW_ROLE,
  ADD_USER,
  ADD_CATEGORY,
  ADD_ARTICLE,
  ADD_PROJECT,
  EDIT_USER,
  EDIT_ROLE,
  EDIT_CATEGORY,
  EDIT_ARTICLE,
  EDIT_PROJECT,
  EDIT_TICKET,
  DELETE_USER,
  DELETE_ROLE,
  DELETE_CATEGORY,
  DELETE_ARTICLE,
  DELETE_PROJECT,
  DELETE_TICKET,
  COMMENT_ARTICLE,
  COMMENT_PROJECT,
  PURPOSE_PROJECT,
  PURPOSE_ARTICLE,
  CHATTING
]
