export const VERIFIED_EMAIL = 'VERIFIED_EMAIL'
export const VERIFIED_PHONE = 'VERIFIED_PHONE'
export const NOTIFIED_EMAIL = 'NOTIFIED_EMAIL'

export default [VERIFIED_EMAIL, VERIFIED_PHONE, NOTIFIED_EMAIL]
